name: 3. Test Stage

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          cd backend
          pip install --no-cache-dir -r requirements.txt

      - name: Run Tests with Pytest
        env:
          DATABASE_URL: postgresql://${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_USER }}:${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_PASSWORD }}@localhost:5432/${{ fromJSON(secrets.MINI_BILTY_SECRET).POSTGRES_DB }}
        run: |
          cd backend
          pytest